apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-old-deployment
  labels:
    app: test-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-dep
  template:
    metadata:
      name: testing-depl
      labels:
        app: test-dep
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
